//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Content
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
        public string Video { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CourseId { get; set; }
        public int OrderId { get; set; }
    
        public virtual Cours Cours { get; set; }
    }
}
